skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sgt_spike = "7y6F1zyzvoeFuMRCxb5NbMYgaMMvw9iKrPLEPRDacz3z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
