skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
seal_spike = "2yoZYJMfBkBhtB6cdRJQQKrX3Me5zFZyT7y4P9kDkRxQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
