skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
observed = "48YybyMgkdzPQN5R3V1xsFHkUMxDvBDBDwW48cRTx2ni"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
